### ISSUE TITLE
wont start period

### ISSUE THREAD

**Issue by ensemblebd** [Hyrules/WinHue3#119]
stacktrace follows...
Program refuses to open. Tried reinstall, tried deleting appdata\roaming and repairing. Tried running in compatibility mode with super privs... no dice.

```
// ^^^^ etc -all ok above- ^^^^^ 
// several lines here showing what it did just prior to stack dump...


DEBUG WinHue3.Utils.HueObjectHelper [ProcessScenes:264] ==> Processing scene : {"name":"Go to sleep end","lights":["4"],"owner":"45WL5nYTMM2eT5z9c2cBuNNoBA4xB1ZCCkzEnw4f","appdata":{},"recycle":true,"locked":true,"picture":"","version":2,"lastupdated":"2017-09-29T02:57:09"}
2017-10-16 23:07:30,860 [1] DEBUG WinHue3.Utils.HueObjectHelper [ProcessScenes:264] ==> Processing scene : {"name":"Recover room 3","lights":["4"],"owner":"45WL5nYTMM2eT5z9c2cBuNNoBA4xB1ZCCkzEnw4f","appdata":{"version":1,"data":"PHd8E_r03_h01"},"recycle":true,"locked":true,"picture":"","version":2,"lastupdated":"2017-10-17T01:49:25"}
2017-10-16 23:07:30,860 [1] DEBUG WinHue3.Utils.HueObjectHelper [ProcessScenes:264] ==> Processing scene : {"name":"Half Bright","lights":["2","9","10"],"owner":"45WL5nYTMM2eT5z9c2cBuNNoBA4xB1ZCCkzEnw4f","appdata":{"version":1,"data":"YQphj_r02_d99"},"recycle":false,"locked":true,"picture":"","version":2,"lastupdated":"2017-10-05T02:50:27"}
2017-10-16 23:07:30,860 [1] DEBUG WinHue3.Utils.HueObjectHelper [ProcessScenes:264] ==> Processing scene : {"name":"Relax","lights":["3","5","6"],"owner":"45WL5nYTMM2eT5z9c2cBuNNoBA4xB1ZCCkzEnw4f","appdata":{"version":1,"data":"thuyi_r01_d01"},"recycle":true,"locked":true,"picture":"","version":2,"lastupdated":"2017-09-29T03:54:35"}
2017-10-16 23:07:30,860 [1] DEBUG WinHue3.Utils.HueObjectHelper [ProcessSensors:480] ==> Processing Sensor : WinHue3.Philips_Hue.HueObjects.SensorObject.Daylight.DaylightSensor
2017-10-16 23:07:30,860 [1] DEBUG WinHue3.Utils.HueObjectHelper [ProcessSensors:496] ==> Sensor is generic sensor.
2017-10-16 23:07:30,860 [1] DEBUG WinHue3.Utils.HueObjectHelper [ProcessSensors:480] ==> Processing Sensor : WinHue3.Philips_Hue.HueObjects.SensorObject.ClipPresence.ClipPresenceSensor
2017-10-16 23:07:30,860 [1] DEBUG WinHue3.Utils.HueObjectHelper [ProcessSensors:496] ==> Sensor is generic sensor.
2017-10-16 23:07:32,946 [1] FATAL WinHue3.App [CurrentDomain_UnhandledException:80] ==> Unexpected Exception : 
System.NullReferenceException: Object reference not set to an instance of an object.
   at WinHue3.Utils.HueObjectHelper.ProcessSensors(Dictionary`2 listsensors) in D:\Documents\Visual Studio 2015\Projects\WinHue3\WinHue3\Utils\HueObjectHelper.cs:line 479
   at WinHue3.Utils.HueObjectHelper.ProcessDataStore(DataStore datastore) in D:\Documents\Visual Studio 2015\Projects\WinHue3\WinHue3\Utils\HueObjectHelper.cs:line 616
   at WinHue3.Utils.HueObjectHelper.<GetBridgeDataStoreAsyncTask>d__27.MoveNext() in D:\Documents\Visual Studio 2015\Projects\WinHue3\WinHue3\Utils\HueObjectHelper.cs:line 577
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WinHue3.ViewModels.MainFormViewModels.MainFormViewModel.<RefreshView>d__168.MoveNext() in D:\Documents\Visual Studio 2015\Projects\WinHue3\WinHue3\ViewModels\MainFormViewModels\MainFormViewModel_Methods.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinHue3.ViewModels.MainFormViewModels.MainFormViewModel.<ChangeBridge>d__163.MoveNext() in D:\Documents\Visual Studio 2015\Projects\WinHue3\WinHue3\ViewModels\MainFormViewModels\MainFormViewModel_Methods.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinHue3.Utils.AsyncRelayCommand.<Execute>d__9.MoveNext() in D:\Documents\Visual Studio 2015\Projects\WinHue3\WinHue3\Utils\AsyncRelayCommand.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WinHue3.App.Main()
```

Was hoping to use this program to edit the rules for my motion sensor, but perhaps I'm in the wrong place after all and this isn't meant to be. Looks like it tries to load ClipPresenceSensor, which i would presume is the motion sensor. Unsupported?

**Comment by Hyrules** [comment]
This is a known issue see the release is #108 and let me know if this fix it.

**Comment by ensemblebd** [comment]
Thank you!! Will test tonight hopefully will do the trick. Hopefully that's it, if so, my apologies for duplicate. Will test and report back

**Comment by Hyrules** [comment]
Is your issue fixed with the latest release ?

**Comment by Hyrules** [comment]
Closing the issue. You can reopen if you still have it.
