### ISSUE TITLE
NullReferenceException when Bridge not responding

### ISSUE THREAD

**Issue by Naharis** [Hyrules/WinHue3#14]
My bridge hiccups regularly, causing an exception shortly thereafter. Occured multiple times.
(don't mind the timestamp of the exception log entry, it seems to use the time after confirming the exception dialog)

2016-08-25 20:19:13,890 [1] DEBUG WinHue3.HueObjectHelper [GetBridgeLight:147] ==> Getting light ID : 1 from Bridge : 192.168.178.103
2016-08-25 20:19:16,890 [1] INFO  WinHue3.MainFormView [MessageAdded:605] ==> {Type : -999, Bridge is not responding at address none.}
2016-08-25 20:19:16,890 [1] DEBUG WinHue3.HueObjectHelper [GetBridgeLight:149] ==> Light : {}
2016-08-25 21:33:47,115 [1] FATAL WinHue3.App [CurrentDomain_UnhandledException:73] ==> Unexpected Exception : 
System.NullReferenceException: Object reference not set to an instance of an object.
   at WinHue3.HueObjectHelper.GetBridgeLight(Bridge bridge, String id) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Utils\HueObjectHelper.cs:line 152
   at WinHue3.MainFormView.RefreshObject(HueObject obj, Boolean logging) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Views\MainFormView.cs:line 814
   at WinHue3.MainFormView._refreshStates_Tick(Object sender, EventArgs e) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Views\MainFormView.cs:line 94
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WinHue3.App.Main()

**Comment by Hyrules** [comment]
This is related to #9. This should be fixed in the next version

**Comment by Hyrules** [comment]
take a look at issue #9  there is the latest version zipped. Try it and let me know if it works.

**Comment by Naharis** [comment]
That new version has been running without exception for multiple hours.
