### ISSUE TITLE
ArgumentNullException when searching for bridges

### ISSUE THREAD

**Issue by kbh01** [Hyrules/WinHue3#15]
After installing Winhue on my newly setup system the following exception occurs every time I start the application:

> 2016-08-28 13:38:51,035 [1] INFO  WinHue3.App [Application_Startup:34] ==> WinHue BETA 17 started
2016-08-28 13:38:54,191 [1] INFO  WinHue3.MainFormView [.ctor:72] ==> Loading bridge from saved settings...
2016-08-28 13:38:54,191 [1] INFO  WinHue3.MainFormView [LoadBridge:560] ==> Loading bridge...
2016-08-28 13:38:54,191 [1] WARN  WinHue3.MainFormView [LoadBridge:566] ==> No bridge paired/Authorized or no default bridge.... Please do the pairing procedure.
2016-08-28 13:38:56,093 [1] INFO  WinHue3.BridgeDetectionPairingView [.ctor:57] ==> Starting bridge detection.
2016-08-28 13:39:08,192 [1] FATAL WinHue3.App [CurrentDomain_UnhandledException:73] ==> Unexpected Exception : 
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at WinHue3.BridgeDetectionPairingView.AssociateApiKey(ObservableCollection`1 bridge) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Views\BridgeDetectionPairingView.cs:line 337
   at WinHue3.BridgeDetectionPairingView.Hue_OnDetectionComplete(Object sender, RunWorkerCompletedEventArgs e) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Views\BridgeDetectionPairingView.cs:line 351
   at HueLib.Hue._detectionBgw_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\HueLib\Hue.cs:line 48
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at WinHue3.MainFormView.DoBridgePairing() in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Views\MainFormView.cs:line 744
   at WinHue3.MainFormView.LoadBridge() in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Views\MainFormView.cs:line 569
   at WinHue3.MainFormView..ctor(Form_EventLog fel) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Views\MainFormView.cs:line 80
   at WinHue3.MainWindow.Window_ContentRendered(Object sender, EventArgs e) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\MainWindow.xaml.cs:line 84
   at System.Windows.Window.OnContentRendered(EventArgs e)
   at System.Windows.Window.<PostContentRendered>b__198_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WinHue3.App.Main()

Could you have a look at this issue?

**Comment by Hyrules** [comment]
Thanks for reporting this bug. I will take a look at this.

**Comment by Hyrules** [comment]
take a look at issue #9 there is the latest version zipped. Try it and let me know if it works.

**Comment by kbh01** [comment]
Thank your for fixing this issue. I can confirm that while the issue still existed with Beta 17 which I tried first (so nothing in my setup has changed) the issue does not occur anymore on Beta 18 and I've succesfully paired the bridge.
