### ISSUE TITLE
Crash while searching for new Lights

### ISSUE THREAD

**Issue by jkersch** [Hyrules/WinHue3#20]
Fresh Start of WinHue3 BETA 18. Paired with first Hue Bridge 2.0 - worked fine.

Pressed the "Search for new Lights" Button.
Crash with the following Stacktrace:

2016-10-12 22:45:21,101 [1] FATAL WinHue3.App [CurrentDomain_UnhandledException:74] ==> Unexpected Exception : 
System.NullReferenceException: Object reference not set to an instance of an object.
   at WinHue3.HueObjectHelper.ProcessSearchResult(Bridge bridge, SearchResult results, Boolean type) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Utils\HueObjectHelper.cs:line 102
   at WinHue3.HueObjectHelper.GetBridgeNewLights(Bridge bridge) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Utils\HueObjectHelper.cs:line 57
   at WinHue3.MainFormView._findlighttimer_Tick(Object sender, EventArgs e) in D:\Documents\Visual Studio 2012\Projects\WinHue3_1\WinHue3\Views\MainFormView.cs:line 735
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WinHue3.App.Main()

**Comment by Hyrules** [comment]
Indeed. I can reproduce this. I will fix it.

**Comment by Hyrules** [comment]
Here you can try this version it should be fixed.
[WinHue 3 BETA 19 Setup.zip](https://github.com/Hyrules/WinHue3/files/525768/WinHue.3.BETA.19.Setup.zip)
